databases:
  - name: db
    databaseName: app
    user: app
    plan: free

services:
  - type: web
    name: backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /api/v1/utils/health-check/
    startCommand: bash scripts/prestart.sh && fastapi run --workers 4 app/main.py
    envVars:
      - key: POSTGRES_SERVER
        fromDatabase:
          name: db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: db
          property: port
      - key: POSTGRES_DB
        fromDatabase:
          name: db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: db
          property: password
      - key: SECRET_KEY
        generateValue: true
      - key: FIRST_SUPERUSER
        value: admin@example.com
      - key: FIRST_SUPERUSER_PASSWORD
        generateValue: true
      - key: PROJECT_NAME
        value: Full Stack FastAPI Project
      - key: ENVIRONMENT
        value: production
      - key: FRONTEND_HOST
        value: https://full-stack-fastapi-template-1z56.onrender.com
      - key: BACKEND_CORS_ORIGINS
        value: https://full-stack-fastapi-template-1z56.onrender.com
      - key: SMTP_HOST
        value: ""
      - key: SMTP_USER
        value: ""
      - key: SMTP_PASSWORD
        value: ""
      - key: EMAILS_FROM_EMAIL
        value: info@example.com
      - key: SENTRY_DSN
        value: ""

  - type: web
    name: frontend
    runtime: static
    buildCommand: cd frontend && npm install -g bun && bun install && bun run build
    staticPublishPath: ./frontend/dist
    buildFilter:
      paths:
        - frontend/**
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://full-stack-fastapi-template-1z56.onrender.com
